model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0205
    log_every_t: 100
    timesteps: 1000
    loss_type: l1
    first_stage_key: image
    cond_stage_key: mask
    image_size: 64
    channels: 3
    concat_mode: true
    cond_stage_trainable: true
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 6
        out_channels: 3
        model_channels: 128
        attention_resolutions:
        - 32
        - 16
        - 8
        num_res_blocks: 2
        channel_mult:
        - 1
        - 4
        - 8
        num_heads: 8
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        ckpt_path: /media/NAS/nas_32/dongkyu/Workspace/latent-diffusion/first_stage_models/vq-f4-lg-e3-z3-n8192/last.ckpt
        embed_dim: 3
        n_embed: 8192
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.modules.SpatialRescaler
      params:
        n_stages: 2
        in_channels: 8
        out_channels: 3

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 32
    num_workers: 16
    wrap: false
    train:
      target: ldm.data.lg-feet-mask.LGFeetTrain
      params:
        size: 256
        interpolation: 'linear'
        use_mask: True
    validation:
      target: ldm.data.lg-feet-mask.LGFeetValidation
      params:
        size: 256
        interpolation: 'linear'
        use_mask: True
    test:
      target: ldm.data.lg-feet-mask.LGFeetTest
      params:
        size: 256
        interpolation: 'linear'
        use_mask: True

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 500
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True
    max_epochs: 500